"""Catálogo oficial GeckoLabs — fonte única de verdade para produtos e preços (centavos USD)."""

PRODUCTS = [
    {
        "slug": "gecko-trace-ultra",
        "name": "GeckoTrace Ultra",
        "tagline": "Kernel eBPF Observability Suite",
        "category": "High-Perf Kernels",
        "version": "v3.4.1",
        "badge": "Flagship 2026",
        "rating": 4.98,
        "reviews_count": 142,
        "featured": True,
        "prices": {"standard": 18900, "enterprise": 74900},
        "currency": "usd",
        "image": "https://images.unsplash.com/photo-1619410283995-43d9134e7656?crop=entropy&cs=srgb&fm=jpg&ixid=M3w4NjA1NTZ8MHwxfHNlYXJjaHw0fHxtaW5pbWFsJTIwdGVjaCUyMHNlcnZlciUyMGNvZGUlMjBzb2Z0d2FyZXxlbnwwfHx8fDE3OTAxODMzMzN8MA&ixlib=rb-4.1.0&q=85",
        "gallery": [
            "https://images.unsplash.com/photo-1619410283995-43d9134e7656?crop=entropy&cs=srgb&fm=jpg&ixid=M3w4NjA1NTZ8MHwxfHNlYXJjaHw0fHxtaW5pbWFsJTIwdGVjaCUyMHNlcnZlciUyMGNvZGUlMjBzb2Z0d2FyZXxlbnwwfHx8fDE3OTAxODMzMzN8MA&ixlib=rb-4.1.0&q=85",
            "https://images.unsplash.com/photo-1607799279861-4dd421887fb3?crop=entropy&cs=srgb&fm=jpg&ixid=M3w4NjA1NTZ8MHwxfHNlYXJjaHwzfHxtaW5pbWFsJTIwdGVjaCUyMHNlcnZlciUyMGNvZGUlMjBzb2Z0d2FyZXxlbnwwfHx8fDE3OTAxODMzMzN8MA&ixlib=rb-4.1.0&q=85",
            "https://images.pexels.com/photos/33349204/pexels-photo-33349204.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
        ],
        "short_desc": "Telemetria de kernel Linux & Darwin com resolução sub-microssegundo, overhead zero e captura automática de memory leaks.",
        "description": "GeckoTrace Ultra é o motor de observabilidade de kernel da GeckoLabs. Instrumentação eBPF compilada sob medida para o seu kernel, com pipeline zero-alloc e exportação direta para Prometheus, Grafana e OTLP.",
        "compatibility": ["Linux x86_64/arm64", "macOS Sonoma/Sequoia", "Docker", "Kubernetes 1.28+"],
        "tags": ["eBPF", "Zero-Overhead", "C99", "Rust Engine"],
        "features": [
            "Resolução de amostragem sub-microssegundo com menos de 0.3% de CPU",
            "Detecção automática de memory leaks e lock contention",
            "Pipeline zero-allocation com ring buffers lock-free",
            "Exportação nativa Prometheus, OTLP e ClickHouse",
            "Perfis de kernel compilados por host (BTF/CO-RE)",
            "Auditoria determinística com hash SHA-256 por build",
        ],
        "requirements": {
            "os": "Linux 5.15+ (x86_64/arm64) ou macOS 14+",
            "memory": "64 MB residente",
            "runtime": "Nenhum — binário estático único",
            "deps": "Kernel com BTF habilitado (CO-RE)",
        },
        "faq": [
            {"q": "O agente impacta a performance do host?", "a": "Não. O pipeline foi projetado com ring buffers lock-free e zero-alocação no caminho quente — overhead medido abaixo de 0.3% de CPU em carga de 450k eventos/s."},
            {"q": "Funciona em kernels customizados?", "a": "Sim. GeckoTrace usa CO-RE (Compile Once, Run Everywhere) com BTF. Kernels sem BTF recebem um pacote de headers gerado automaticamente."},
            {"q": "Como funciona a licença Enterprise?", "a": "Licença de site ilimitada com suporte a air-gap, SLA de 24h e direito a builds assinados sob demanda."},
            {"q": "Posso testar antes de comprar?", "a": "Toda licença inclui 14 dias de garantia de reembolso integral, sem perguntas."},
        ],
    },
    {
        "slug": "prism-mesh-addon",
        "name": "PrismMesh",
        "tagline": "Envoy & Istio Service Mesh Accelerator",
        "category": "Architecture Runtimes",
        "version": "v2.1.0",
        "badge": "Architect Pick",
        "rating": 4.92,
        "reviews_count": 89,
        "featured": True,
        "prices": {"standard": 14900, "enterprise": 59000},
        "currency": "usd",
        "image": "https://images.unsplash.com/photo-1640904422940-f3070d65ae29?crop=entropy&cs=srgb&fm=jpg&ixid=M3w3NDQ2Mzl8MHwxfHNlYXJjaHw0fHxtaW5pbWFsJTIwYWJzdHJhY3QlMjBkYXJrJTIwdGVjaG5vbG9neSUyMGdyaWQlMjAzZHxlbnwwfHx8fDE3OTAxODMzNDJ8MA&ixlib=rb-4.1.0&q=85",
        "gallery": [
            "https://images.unsplash.com/photo-1640904422940-f3070d65ae29?crop=entropy&cs=srgb&fm=jpg&ixid=M3w3NDQ2Mzl8MHwxfHNlYXJjaHw0fHxtaW5pbWFsJTIwYWJzdHJhY3QlMjBkYXJrJTIwdGVjaG5vbG9neSUyMGdyaWQlMjAzZHxlbnwwfHx8fDE3OTAxODMzNDJ8MA&ixlib=rb-4.1.0&q=85",
            "https://images.pexels.com/photos/26954236/pexels-photo-26954236.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
            "https://images.unsplash.com/photo-1684503830683-108f3e0fd03f?crop=entropy&cs=srgb&fm=jpg&ixid=M3w3NDQ2Mzl8MHwxfHNlYXJjaHwyfHxtaW5pbWFsJTIwYWJzdHJhY3QlMjBkYXJrJTIwdGVjaG5vbG9neSUyMGdyaWQlMjAzZHxlbnwwfHx8fDE3OTAxODMzNDJ8MA&ixlib=rb-4.1.0&q=85",
        ],
        "short_desc": "Plugin de protocolo binário de alta vazão que compila árvores de roteamento dinâmicas em código de máquina acelerado por SIMD.",
        "description": "PrismMesh injeta um caminho de dados compilado diretamente no Envoy: rotas, retries e circuit breakers viram código de máquina SIMD, eliminando o custo de interpretação por request.",
        "compatibility": ["Envoy v1.30+", "Istio 1.22+", "WASM Edge"],
        "tags": ["WASM", "SIMD", "Low-Latency", "Networking"],
        "features": [
            "Roteamento compilado em SIMD (AVX-512/NEON)",
            "P99 de data plane reduzido em até 62%",
            "Hot-reload de rotas sem restart do proxy",
            "Filtro WASM assinado e verificado por hash",
            "Telemetria de mesh embutida com cardinalidade controlada",
            "Rollback atômico de configuração em menos de 50ms",
        ],
        "requirements": {
            "os": "Linux x86_64/arm64",
            "memory": "32 MB por sidecar",
            "runtime": "Envoy v1.30+ ou Istio 1.22+",
            "deps": "WASM runtime (V8/Wasmtime) habilitado",
        },
        "faq": [
            {"q": "Preciso reescrever minhas configs do Envoy?", "a": "Não. PrismMesh consome os mesmos xDS resources e compila as árvores de decisão existentes."},
            {"q": "É compatível com Istio ambiente mesh?", "a": "Sim, incluindo ambient mesh e sidecar clássico a partir do Istio 1.22."},
            {"q": "Como o filtro é distribuído?", "a": "Como módulo WASM assinado, verificado por hash SHA-256 no carregamento."},
        ],
    },
    {
        "slug": "poly-vault-crypto",
        "name": "PolyVault HSM",
        "tagline": "Cryptographic Secret Enclave",
        "category": "Security Vaults",
        "version": "v4.0.2",
        "badge": "FIPS-Ready",
        "rating": 4.99,
        "reviews_count": 210,
        "featured": True,
        "prices": {"standard": 22900, "enterprise": 89900},
        "currency": "usd",
        "image": "https://images.unsplash.com/photo-1562813733-b31f71025d54?crop=entropy&cs=srgb&fm=jpg&ixid=M3w4NjAzNTl8MHwxfHNlYXJjaHwxfHxjeWJlciUyMHNlY3VyaXR5JTIwZGV2ZWxvcGVyJTIwdGVybWluYWwlMjBkYXJrfGVufDB8fHx8MTc5MDE4MzMzM3ww&ixlib=rb-4.1.0&q=85",
        "gallery": [
            "https://images.unsplash.com/photo-1562813733-b31f71025d54?crop=entropy&cs=srgb&fm=jpg&ixid=M3w4NjAzNTl8MHwxfHNlYXJjaHwxfHxjeWJlciUyMHNlY3VyaXR5JTIwZGV2ZWxvcGVyJTIwdGVybWluYWwlMjBkYXJrfGVufDB8fHx8MTc5MDE4MzMzM3ww&ixlib=rb-4.1.0&q=85",
            "https://images.pexels.com/photos/5380664/pexels-photo-5380664.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
            "https://images.unsplash.com/photo-1640904422940-f3070d65ae29?crop=entropy&cs=srgb&fm=jpg&ixid=M3w3NDQ2Mzl8MHwxfHNlYXJjaHw0fHxtaW5pbWFsJTIwYWJzdHJhY3QlMjBkYXJrJTIwdGVjaG5vbG9neSUyMGdyaWQlMjAzZHxlbnwwfHx8fDE3OTAxODMzNDJ8MA&ixlib=rb-4.1.0&q=85",
        ],
        "short_desc": "Enclave criptográfico pós-quântico com rotação de segredos zero-knowledge para arquiteturas distribuídas.",
        "description": "PolyVault HSM é um daemon de enclave com criptografia de reticulados (Kyber/Dilithium), rotação automática de segredos e atestado remoto — pronto para ambientes regulados.",
        "compatibility": ["AWS Nitro", "GCP Confidential VM", "Bare Metal TPM 2.0"],
        "tags": ["Post-Quantum", "HSM", "Zero-Trust", "Go & Rust"],
        "features": [
            "Criptografia pós-quântica (ML-KEM / ML-DSA)",
            "Rotação zero-knowledge de segredos sem downtime",
            "Atestado remoto com TPM 2.0 e Nitro Enclaves",
            "Trilha de auditoria imutável assinada",
            "API compatível com PKCS#11 e KMIP",
            "Políticas de acesso compiladas (OPA/Rego)",
        ],
        "requirements": {
            "os": "Linux x86_64 (kernel 5.10+)",
            "memory": "128 MB residente",
            "runtime": "Binário estático + daemon systemd",
            "deps": "TPM 2.0, Nitro Enclave ou Confidential VM",
        },
        "faq": [
            {"q": "É certificado FIPS 140-3?", "a": "O módulo criptográfico está em processo final de validação FIPS 140-3; builds FIPS-ready já estão disponíveis."},
            {"q": "Posso usar sem hardware HSM?", "a": "Sim. PolyVault opera em modo software com a mesma API, ideal para staging e CI."},
            {"q": "Como funciona a rotação zero-knowledge?", "a": "Os segredos são re-cifrados dentro do enclave sem jamais serem expostos em claro — nem para operadores."},
        ],
    },
    {
        "slug": "gecko-lens-ide",
        "name": "GeckoLens AI",
        "tagline": "VSCode & JetBrains Architecture Co-Pilot",
        "category": "IDE Plugins",
        "version": "v1.8.4",
        "badge": "Community Favorite",
        "rating": 4.88,
        "reviews_count": 340,
        "featured": True,
        "prices": {"standard": 7900, "enterprise": 29000},
        "currency": "usd",
        "image": "https://images.unsplash.com/photo-1607799279861-4dd421887fb3?crop=entropy&cs=srgb&fm=jpg&ixid=M3w4NjA1NTZ8MHwxfHNlYXJjaHwzfHxtaW5pbWFsJTIwdGVjaCUyMHNlcnZlciUyMGNvZGUlMjBzb2Z0d2FyZXxlbnwwfHx8fDE3OTAxODMzMzN8MA&ixlib=rb-4.1.0&q=85",
        "gallery": [
            "https://images.unsplash.com/photo-1607799279861-4dd421887fb3?crop=entropy&cs=srgb&fm=jpg&ixid=M3w4NjA1NTZ8MHwxfHNlYXJjaHwzfHxtaW5pbWFsJTIwdGVjaCUyMHNlcnZlciUyMGNvZGUlMjBzb2Z0d2FyZXxlbnwwfHx8fDE3OTAxODMzMzN8MA&ixlib=rb-4.1.0&q=85",
            "https://images.unsplash.com/photo-1619410283995-43d9134e7656?crop=entropy&cs=srgb&fm=jpg&ixid=M3w4NjA1NTZ8MHwxfHNlYXJjaHw0fHxtaW5pbWFsJTIwdGVjaCUyMHNlcnZlciUyMGNvZGUlMjBzb2Z0d2FyZXxlbnwwfHx8fDE3OTAxODMzMzN8MA&ixlib=rb-4.1.0&q=85",
            "https://images.pexels.com/photos/33349204/pexels-photo-33349204.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
        ],
        "short_desc": "Visualizador estrutural de dependências e detector de architectural smells, 100% air-gapped em modelos locais.",
        "description": "GeckoLens AI analisa a AST do seu monorepo inteiro localmente — nenhum byte sai da sua máquina. Detecta acoplamentos, ciclos e violações de camada em tempo real dentro do editor.",
        "compatibility": ["VS Code 1.85+", "IntelliJ IDEA 2024+", "NeoVim 0.10+"],
        "tags": ["Air-Gapped", "IDE Plugin", "Local LLM", "AST Analyzer"],
        "features": [
            "Grafo de dependências interativo em tempo real",
            "Detecção de architectural smells e ciclos",
            "Modelos locais quantizados — zero telemetria",
            "Regras de arquitetura como código (YAML)",
            "Suporte a 14 linguagens via tree-sitter",
            "Baseline de arquitetura com diff por PR",
        ],
        "requirements": {
            "os": "Windows 11, macOS 14+, Linux",
            "memory": "2 GB para modelos locais (quantizados)",
            "runtime": "Plugin nativo do editor",
            "deps": "Nenhuma — funciona offline",
        },
        "faq": [
            {"q": "Meu código é enviado para algum servidor?", "a": "Nunca. Toda análise roda localmente em modelos quantizados embutidos no plugin."},
            {"q": "Funciona em monorepos grandes?", "a": "Sim — o índice de AST é incremental e paralelo; monorepos com 5M+ linhas abrem em segundos."},
            {"q": "Posso definir minhas próprias regras?", "a": "Sim, via arquivos YAML versionados no próprio repositório."},
        ],
    },
    {
        "slug": "stream-citus-sync",
        "name": "StreamSync Postgres",
        "tagline": "Change Data Capture Kernel",
        "category": "Observability Add-ons",
        "version": "v2.0.8",
        "badge": "High Concurrency",
        "rating": 4.95,
        "reviews_count": 67,
        "featured": False,
        "prices": {"standard": 12900, "enterprise": 49000},
        "currency": "usd",
        "image": "https://images.unsplash.com/photo-1753998943413-8cba1b923c0e?crop=entropy&cs=srgb&fm=jpg&ixid=M3w4NjAzNTl8MHwxfHNlYXJjaHw0fHxjeWJlciUyMHNlY3VyaXR5JTIwZGV2ZWxvcGVyJTIwdGVybWluYWwlMjBkYXJrfGVufDB8fHx8MTc5MDE4MzMzM3ww&ixlib=rb-4.1.0&q=85",
        "gallery": [
            "https://images.unsplash.com/photo-1753998943413-8cba1b923c0e?crop=entropy&cs=srgb&fm=jpg&ixid=M3w4NjAzNTl8MHwxfHNlYXJjaHw0fHxjeWJlciUyMHNlY3VyaXR5JTIwZGV2ZWxvcGVyJTIwdGVybWluYWwlMjBkYXJrfGVufDB8fHx8MTc5MDE4MzMzM3ww&ixlib=rb-4.1.0&q=85",
            "https://images.unsplash.com/photo-1619410283995-43d9134e7656?crop=entropy&cs=srgb&fm=jpg&ixid=M3w4NjA1NTZ8MHwxfHNlYXJjaHw0fHxtaW5pbWFsJTIwdGVjaCUyMHNlcnZlciUyMGNvZGUlMjBzb2Z0d2FyZXxlbnwwfHx8fDE3OTAxODMzMzN8MA&ixlib=rb-4.1.0&q=85",
            "https://images.pexels.com/photos/5380664/pexels-photo-5380664.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
        ],
        "short_desc": "Streamer de replicação lógica WAL sem locks, entregando 450k eventos/s direto em Kafka e ClickHouse.",
        "description": "StreamSync lê o WAL do PostgreSQL com protocolo lógico nativo e publica eventos ordenados por transação em Kafka, ClickHouse e webhooks — sem triggers, sem polling, sem locks.",
        "compatibility": ["PostgreSQL 14, 15, 16", "Citus 12+", "Neon Cloud"],
        "tags": ["CDC", "Postgres", "Kafka", "WAL Streaming"],
        "features": [
            "450k eventos/s por instância (benchmark público)",
            "Ordenação transacional garantida (LSN)",
            "Schema evolution automática com registry",
            "Backfill inicial sem locks (snapshot consistente)",
            "Sinks nativos: Kafka, ClickHouse, Webhook, S3",
            "Replay histórico por slot de replicação",
        ],
        "requirements": {
            "os": "Linux x86_64/arm64 ou container",
            "memory": "96 MB residente",
            "runtime": "Binário único ou imagem distroless",
            "deps": "PostgreSQL 14+ com wal_level=logical",
        },
        "faq": [
            {"q": "Preciso instalar extensão no Postgres?", "a": "Não. StreamSync usa o protocolo de replicação lógica nativo (pgoutput)."},
            {"q": "E se o consumidor cair?", "a": "O slot de replicação preserva a posição; ao retomar, o stream continua exatamente do LSN confirmado."},
            {"q": "Suporta Citus distribuído?", "a": "Sim — um worker por shard coordenado pelo aggregator, com ordenação global opcional."},
        ],
    },
    {
        "slug": "apex-wasm-runtime",
        "name": "ApexWasm",
        "tagline": "Edge Micro-Container Virtualizer",
        "category": "Architecture Runtimes",
        "version": "v1.4.0",
        "badge": "Cold-Start <1ms",
        "rating": 4.91,
        "reviews_count": 52,
        "featured": False,
        "prices": {"standard": 16900, "enterprise": 64000},
        "currency": "usd",
        "image": "https://images.unsplash.com/photo-1684503830683-108f3e0fd03f?crop=entropy&cs=srgb&fm=jpg&ixid=M3w3NDQ2Mzl8MHwxfHNlYXJjaHwyfHxtaW5pbWFsJTIwYWJzdHJhY3QlMjBkYXJrJTIwdGVjaG5vbG9neSUyMGdyaWQlMjAzZHxlbnwwfHx8fDE3OTAxODMzNDJ8MA&ixlib=rb-4.1.0&q=85",
        "gallery": [
            "https://images.unsplash.com/photo-1684503830683-108f3e0fd03f?crop=entropy&cs=srgb&fm=jpg&ixid=M3w3NDQ2Mzl8MHwxfHNlYXJjaHwyfHxtaW5pbWFsJTIwYWJzdHJhY3QlMjBkYXJrJTIwdGVjaG5vbG9neSUyMGdyaWQlMjAzZHxlbnwwfHx8fDE3OTAxODMzNDJ8MA&ixlib=rb-4.1.0&q=85",
            "https://images.pexels.com/photos/26954236/pexels-photo-26954236.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
            "https://images.unsplash.com/photo-1640904422940-f3070d65ae29?crop=entropy&cs=srgb&fm=jpg&ixid=M3w3NDQ2Mzl8MHwxfHNlYXJjaHw0fHxtaW5pbWFsJTIwYWJzdHJhY3QlMjBkYXJrJTIwdGVjaG5vbG9neSUyMGdyaWQlMjAzZHxlbnwwfHx8fDE3OTAxODMzNDJ8MA&ixlib=rb-4.1.0&q=85",
        ],
        "short_desc": "Runtime sandboxed micro-virtualizado com cold boot de 350 microssegundos para edge computing distribuído.",
        "description": "ApexWasm executa módulos WebAssembly em sandboxes micro-virtualizadas com isolamento de capability — cold start medido em microssegundos, não milissegundos.",
        "compatibility": ["Cloudflare Workers", "Fastly Compute", "Self-Hosted Edge"],
        "tags": ["WASM", "Serverless", "Edge", "Sandboxing"],
        "features": [
            "Cold boot de 350µs (medido, não estimado)",
            "Isolamento por capability (WASI Preview 2)",
            "Densidade de 10k isolados por host",
            "Snapshot/restore de memória em <1ms",
            "Compilação AOT com cache distribuído",
            "API compatível com OCI para imagens WASM",
        ],
        "requirements": {
            "os": "Linux x86_64/arm64 (kernel 5.15+)",
            "memory": "16 MB base + 512 KB por isolado",
            "runtime": "Binário estático único",
            "deps": "Nenhuma",
        },
        "faq": [
            {"q": "Substitui containers Docker?", "a": "Para workloads de request/response curtos, sim — com isolamento equivalente e 100x menos overhead."},
            {"q": "Quais linguagens compilam para ApexWasm?", "a": "Rust, Go (TinyGo), C/C++, AssemblyScript e qualquer alvo WASM/WASI Preview 2."},
            {"q": "Funciona on-premise?", "a": "Sim, o runtime é self-hosted e opera air-gapped com licença Enterprise."},
        ],
    },

    PROMO_CODES = {
    "GECKO-LAUNCH-20": 20,
    "ARCHITECT-10": 10,
}

PLATFORMS = ["macos-arm64", "macos-x64", "linux-amd64", "windows-x64"]